# Site settings
title: REBIPP - Plant-Pollinator Interactions Vocabulary
description: Website for the REBIPP Plant-Pollinator Interactions vocabulary.
url: "https://ppi.rebipp.org.br"

navbar:
  left:
  - text: Terms
    menu:
    - text: 'Vocabulary'
      href: terms/
    - text: 'Controlled Vocabulary':
      href: cv/
  - text: Guides
    menu:
    - text: PPI Quick Reference
      href: terms/
    - text: Text (Darwin Core Archive)
      href: text/
    - text: XML
      href: xml/
    - text: RDF
      href: rdf/
  - text: Namespace policy
    href: namespace/
  - text: Questions & Answers (separate site)
    href: https://github.com/rebipp/ppi-qa/blob/master/README.
  right:
  - text: GitHub
    href: https://github.com/rebipp/ppi

js: >-
  $(document).ready(function() {
      // In quick reference guide: add divider in sidebar after UseWithIRI
      $("a[href='#usewithiri']", "#theme-sidebar-nav").parent().addClass("theme-divider-below");
  });

# Build settings
markdown: kramdown
# theme: tdwg-theme-jekyll
remote_theme: rebipp/tdwg-theme-jekyll
plugins:
  - jekyll-feed
